In [30]:
from IPython.display import display, HTML

# Título Principal del Proyecto - Portada de Presentación
titulo_proyecto_html = """
<div style="background-color: #232f3e; color: white; padding: 50px; border-radius: 15px; text-align: center; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; border-bottom: 8px solid #ff9900;">
    <h1 style="color: #ff9900; font-size: 42px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 2px;">
        PROYECTO: AMAZON BIG DATA ANALYTICS
    </h1>
    <h2 style="font-size: 22px; font-weight: 300; margin-top: 0; color: #ffffff;">
        Análisis Multidimensional de Comportamiento del Consumidor mediante Apache Spark
    </h2>
    <hr style="border: 0; height: 2px; background-image: linear-gradient(to right, transparent, #ff9900, transparent); width: 80%; margin: 25px auto;">
    
    <div style="display: flex; justify-content: center; gap: 40px; margin-top: 20px; font-size: 16px;">
        <span><b>Materia:</b> Big Data </span>
        <span><b>Avance:</b> 2do Reporte Técnico</span>
    </div>
    
    <div style="margin-top: 40px; padding: 15px; background: rgba(255,255,255,0.1); border-radius: 8px; display: inline-block;">
        <p style="margin: 0; font-size: 14px; color: #ff9900;"><b>PERIODO DE EJECUCIÓN</b></p>
        <p style="margin: 5px 0 0 0; font-size: 18px; letter-spacing: 1px;">ABRIL 2026 - MAYO 2026</p>
    </div>
</div>
"""

display(HTML(titulo_proyecto_html))

In [16]:
from IPython.display import display, HTML

intro_html = """
<div style="font-family: 'Segoe UI', sans-serif; padding: 25px; background-color: #ffffff; border: 1px solid #232f3e; border-radius: 10px;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900;">3. Introducción</h2>
    <p style="font-size: 1.1em; color: #333;">
        El presente proyecto surge de la necesidad de procesar grandes volúmenes de datos generados por los usuarios de <b>Amazon</b>. En un entorno de Big Data, la información a menudo llega de forma "sucia" o no estructurada.
    </p>
    <div style="background-color: #fcf3cf; padding: 15px; border-radius: 5px; margin-top: 10px;">
        <strong>El Reto:</strong> Transformar millones de reseñas con formatos inconsistentes en una base de datos analítica que permita medir la satisfacción del cliente de manera precisa y escalable mediante <b>Apache Spark</b>.
    </div>
</div>
"""
display(HTML(intro_html))

In [15]:
from IPython.display import display, HTML

# Diseño de Objetivos y Justificación
desarrollo_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">4. Desarrollo: Metas del Proyecto</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #ff9900;">
            <h3 style="margin-top: 0; color: #146eb4;">a) Objetivos</h3>
            <ul style="padding-left: 20px;">
                <li><b>General:</b> Procesar y modelar datos masivos de Amazon para extraer tendencias de consumo.</li>
                <li><b>Técnico:</b> Implementar un proceso ETL (Extracción, Transformación, Carga) robusto en PySpark.</li>
                <li><b>Analítico:</b> Diseñar un esquema multidimensional (Estrella) para optimizar consultas SQL de alto rendimiento.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #146eb4;">
            <h3 style="margin-top: 0; color: #ff9900;">b) Justificación</h3>
            <p>
                El análisis de sentimiento y ratings es crítico para Amazon. Sin embargo, los datos crudos presentan <b>inconsistencias de formato</b> (texto mezclado con números). 
            </p>
            <p>
                <b>Justificación técnica:</b> El uso de Apache Spark se justifica por su capacidad de manejar <i>Lazy Evaluation</i> y transformaciones complejas en memoria, permitiendo corregir errores de tipado que detendrían un análisis convencional en Excel o bases de datos relacionales simples.
            </p>
        </div>
    </div>
</div>
"""
display(HTML(desarrollo_html))

In [17]:
from IPython.display import display, HTML

fuente_datos_html = """
<div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; background-color: #ffffff; border-radius: 10px; border: 1px solid #ff9900;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900;">4-c. Fuentes de Datos y Estructura</h2>
    
    <div style="display: flex; gap: 20px; align-items: start;">
        <div style="flex: 1;">
            <h3 style="color: #146eb4;">Origen del Dataset</h3>
            <p>Se utiliza el dataset <b>"Amazon Product Reviews"</b> obtenido de Kaggle. Este archivo contiene la retroalimentación directa de los clientes sobre diversos productos globales.</p>
            
            <h3 style="color: #146eb4;">Estructura del Archivo</h3>
            <ul>
                <li><b>Formato:</b> CSV (Comma Separated Values)</li>
                <li><b>Registros:</b> +100,000 filas procesadas</li>
                <li><b>Columnas Clave:</b> 
                    <i>Reviewer Name, Rating, Country, Review Date, Product Category.</i>
                </li>
            </ul>
        </div>
        
        <div style="flex: 1; background-color: #f9f9f9; padding: 15px; border-radius: 8px; border: 1px dashed #ccc;">
            <h3 style="color: #232f3e; text-align: center;">Modelo de Datos</h3>
            <p style="font-size: 0.9em; text-align: center;">
                Implementamos un <b>Modelo en Estrella</b> para separar la métrica (Rating) de sus dimensiones descriptivas.
            </p>
            <div style="text-align: center; font-size: 1.2em;">
                <b>Dim_Usuario</b> ← <b>HECHOS</b> → <b>Dim_País</b><br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↑<br>
                <b>Dim_Tiempo</b>
            </div>
        </div>
    </div>
    
    <div style="margin-top: 20px; padding: 10px; background-color: #eaf2f8; border-radius: 5px;">
        <small><i>*Nota: El Diagrama en Estrella detallado se visualiza en la siguiente sección técnica del Notebook.</i></small>
    </div>
</div>
"""
display(HTML(fuente_datos_html))

In [20]:
from IPython.display import display, HTML

# Diseño de Alcances y Limitaciones con formato de "Tarjetas de Objetivos"
alcances_estilo_objetivos_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">4-d. Desarrollo: Alcances y Limitaciones</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #16a085;">
            <h3 style="margin-top: 0; color: #16a085;">✅ Alcances</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li><b>Procesamiento Masivo:</b> Capacidad de manejar +100,000 registros mediante arquitectura distribuida.</li>
                <li><b>Limpieza Automatizada:</b> Normalización de Ratings inconsistentes usando expresiones regulares en PySpark.</li>
                <li><b>Análisis Geográfico:</b> Segmentación precisa por país para identificar mercados clave.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #e67e22;">
            <h3 style="margin-top: 0; color: #e67e22;">⚠️ Limitaciones</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li><b>Dataset Estático:</b> El análisis se basa en un archivo histórico, no en una conexión API en tiempo real.</li>
                <li><b>Profundidad de Texto:</b> No se realiza análisis de sentimientos complejo (NLP) en el cuerpo de la reseña en esta fase.</li>
                <li><b>Dependencia de Origen:</b> Los resultados están limitados a la veracidad de los datos provistos por el CSV original.</li>
            </ul>
        </div>
    </div>
</div>
"""
display(HTML(alcances_estilo_objetivos_html))

In [22]:
from IPython.display import display, HTML

# Diseño de Resultados Esperados con el formato de tarjetas
resultados_estilo_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">4-e. Desarrollo: Resultados Esperados</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #3498db;">
            <h3 style="margin-top: 0; color: #3498db;">📊 Resultados Analíticos</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li><b>KPIs Precisos:</b> Obtención de métricas de satisfacción (Rating promedio) totalmente confiables tras la limpieza de datos.</li>
                <li><b>Insights Geográficos:</b> Identificación de los mercados con mayor volumen de interacción y mejores calificaciones.</li>
                <li><b>Tendencias Temporales:</b> Visualización del comportamiento de las reseñas a lo largo de las 8 semanas de estudio.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #9b59b6;">
            <h3 style="margin-top: 0; color: #9b59b6;">⚙️ Entregables Técnicos</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li><b>Base de Datos Optimizada:</b> Implementación física del esquema en estrella en memoria de Spark para consultas veloces.</li>
                <li><b>Pipeline de Limpieza:</b> Un script de PySpark automatizado y reutilizable para futuros datasets de Amazon.</li>
                <li><b>Documentación Técnica:</b> Reporte detallado del proceso ETL y la resolución del problema de tipos de datos.</li>
            </ul>
        </div>
    </div>
</div>
"""
display(HTML(resultados_estilo_html))

In [25]:
from IPython.display import display, HTML

# Configuración del Cronograma de 8 Semanas (Finaliza en Mayo)
cronograma_html = """
<div style="font-family: 'Segoe UI', sans-serif; padding: 20px; border: 1px solid #ccd1d1; border-radius: 12px; background-color: #fdfefe;">
    <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">Planificación del Proyecto (Gantt Chart)</h2>
    <p style="text-align: center; color: #7f8c8d; margin-bottom: 20px;">Duración: 8 Semanas (Abril - Mayo 2026)</p>
    
    <table style="width: 100%; border-collapse: collapse; table-layout: fixed;">
        <thead>
            <tr style="background-color: #f2f3f4; text-align: center;">
                <th style="width: 30%; padding: 10px; border: 1px solid #ddd;">Actividades / Fases</th>
                <th style="padding: 10px; border: 1px solid #ddd; background-color: #ebf5fb;">Abril (Sem 1-4)</th>
                <th style="padding: 10px; border: 1px solid #ddd; background-color: #fef9e7;">Mayo (Sem 5-8)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;"><b>Fase I:</b> Ingesta y Configuración</td>
                <td style="border: 1px solid #ddd; position: relative;">
                    <div style="background: #3498db; width: 90%; height: 20px; border-radius: 10px; margin: auto; color: white; font-size: 10px; line-height: 20px; text-align: center;">100%</div>
                </td>
                <td style="border: 1px solid #ddd;"></td>
            </tr>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;"><b>Fase II:</b> Limpieza y ETL (Regex)</td>
                <td style="border: 1px solid #ddd; position: relative;">
                    <div style="background: #3498db; width: 90%; height: 20px; border-radius: 10px; margin-left: 10%; color: white; font-size: 10px; line-height: 20px; text-align: center;">100%</div>
                </td>
                <td style="border: 1px solid #ddd;"></td>
            </tr>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;"><b>Fase III:</b> Modelado Estrella</td>
                <td style="border: 1px solid #ddd;"></td>
                <td style="border: 1px solid #ddd; position: relative;">
                    <div style="background: #f1c40f; width: 90%; height: 20px; border-radius: 10px; margin: auto; color: white; font-size: 10px; line-height: 20px; text-align: center;">100%</div>
                </td>
            </tr>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;"><b>Fase IV:</b> Consultas SQL y Presentación</td>
                <td style="border: 1px solid #ddd;"></td>
                <td style="border: 1px solid #ddd; position: relative;">
                    <div style="background: #27ae60; width: 90%; height: 20px; border-radius: 10px; margin-left: 10%; color: white; font-size: 10px; line-height: 20px; text-align: center;">EN PROCESO</div>
                </td>
            </tr>
        </tbody>
    </table>
    <br>
    <div style="font-size: 12px; color: #566573;">
        * <b>Nota:</b> El proyecto concluye la última semana de mayo con la presentación final de los 15 minutos.
    </div>
</div>
"""

display(HTML(cronograma_html))

In [23]:
from IPython.display import display, HTML

puntos_avance_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">1 y 2. Resumen y Mejoras del Avance Anterior</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #7f8c8d;">
            <h3 style="margin-top: 0; color: #232f3e;">📋 Puntos Resumidos</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li>Identificación del dataset de Amazon con +100k registros.</li>
                <li>Definición del problema: Inconsistencia en formatos de Rating.</li>
                <li>Elección de Apache Spark como motor de procesamiento distribuido.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #2ecc71;">
            <h3 style="margin-top: 0; color: #27ae60;">🛠️ Correcciones y Mejoras</h3>
            <ul style="padding-left: 20px; color: #333;">
                <li><b>Optimización de Memoria:</b> Se ajustó la configuración de Spark para evitar desbordamientos.</li>
                <li><b>Limpieza con Regex:</b> Se corrigió la lógica de extracción para capturar solo el dígito numérico del Rating.</li>
                <li><b>Esquema Fijo:</b> Se definió un esquema para evitar la inferencia lenta en archivos masivos.</li>
            </ul>
        </div>
    </div>
</div>
"""
display(HTML(puntos_avance_html))

In [24]:
diseno_bd_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">3 y 4. Diseño y Creación Multidimensional</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #e74c3c;">
            <h3 style="margin-top: 0; color: #c0392b;">📐 Diseño (Diagrama)</h3>
            <p>Se implementó un <b>Esquema en Estrella</b> donde:</p>
            <ul style="padding-left: 20px;">
                <li><b>Hechos:</b> Tabla central con Ratings y llaves foráneas.</li>
                <li><b>Dimensiones:</b> Tablas de Usuario, Geografía (País) y Tiempo.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #f39c12;">
            <h3 style="margin-top: 0; color: #d35400;">🚀 Creación con PySpark</h3>
            <p>Utilizando <code>spark.sql</code> y DataFrames:</p>
            <ul style="padding-left: 20px;">
                <li>Particionamiento de datos por País para consultas rápidas.</li>
                <li>Persistencia en memoria (Cache) para optimizar las consultas SQL.</li>
            </ul>
        </div>
    </div>
</div>
"""
display(HTML(diseno_bd_html))

### 3. Diseño de Base de Datos Multidimensional (Modelo en Estrella)

In [12]:
from IPython.display import display, HTML

# Diseño mejorado para que no se encimen los elementos
estrella_final = """
<div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; background-color: #ffffff; border: 1px solid #ddd; border-radius: 10px;">
    <h2 style="text-align: center; color: #333;">Esquema en Estrella: Análisis de Amazon Reviews</h2>
    
    <table style="width: 100%; border-collapse: separate; border-spacing: 20px; table-layout: fixed;">
        <tr>
            <td></td>
            
            <td style="border: 2px solid #f1c40f; border-radius: 10px; background-color: #fef9e7; padding: 15px; text-align: center;">
                <b style="color: #9a7d0a; font-size: 1.1em;">DIM_TIEMPO</b><hr>
                Fecha_PK (String)<br>
                Año | Mes | Día
            </td>
            
            <td></td>
        </tr>
        
        <tr>
            <td style="border: 2px solid #3498db; border-radius: 10px; background-color: #ebf5fb; padding: 15px; text-align: center;">
                <b style="color: #21618c; font-size: 1.1em;">DIM_USUARIO</b><hr>
                Usuario_PK (String)<br>
                Profile_Link<br>
                Review_Count
            </td>
            
            <td style="border: 4px solid #e74c3c; border-radius: 15px; background-color: #f9ebea; padding: 25px; text-align: center; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
                <b style="color: #922b21; font-size: 1.3em;">HECHOS_REVIEWS</b><hr style="border: 1px solid #922b21;">
                <span style="font-weight: bold; font-size: 1.1em;">Rating (Métrica Int)</span><br>
                <span style="color: #666; font-size: 0.9em;">(1 al 5 estrellas)</span>
                <hr style="border: 1px dashed #922b21;">
                Usuario_FK<br>
                Pais_FK<br>
                Fecha_FK
            </td>
            
            <td style="border: 2px solid #2ecc71; border-radius: 10px; background-color: #eafaf1; padding: 15px; text-align: center;">
                <b style="color: #1d8348; font-size: 1.1em;">DIM_PAIS</b><hr>
                Pais_PK (String)<br>
                Continente
            </td>
        </tr>
    </table>
    
    <p style="text-align: center; margin-top: 20px; color: #555; font-style: italic;">
        Lógica del Modelo: Las dimensiones proveen el contexto (quién, dónde, cuándo) <br>
        mientras que la tabla central almacena la métrica clave (cuánto rating).
    </p>
</div>
"""

display(HTML(estrella_final))

In [26]:
etl_consultas_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">5 y 6. Proceso ETL y Análisis de Datos</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #34495e;">
            <h3 style="margin-top: 0; color: #2c3e50;">🔄 ETL (Extracción y Carga)</h3>
            <ul style="padding-left: 20px;">
                <li><b>Extracción:</b> Lectura de CSV desde entorno local/cloud.</li>
                <li><b>Transformación:</b> Uso de <code>regexp_extract</code> y <code>try_cast</code>.</li>
                <li><b>Carga:</b> Registro de vistas temporales para SQL.</li>
            </ul>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #3498db;">
            <h3 style="margin-top: 0; color: #2980b9;">🔍 Consultas SQL Clave</h3>
            <p>Obtención de datos relevantes como:</p>
            <ul style="padding-left: 20px;">
                <li>Promedio de Rating por País.</li>
                <li>Usuarios con mayor cantidad de reseñas.</li>
                <li>Distribución de calificaciones globales.</li>
            </ul>
        </div>
    </div>
</div>
"""
display(HTML(etl_consultas_html))

In [10]:
import os
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, regexp_extract, round

# 1. Iniciar la sesión de Spark
spark = SparkSession.builder.appName("Amazon_Reviews_Final").getOrCreate()

# 2. Definir la ruta a tu carpeta archive (8)
base_path = r"C:\Users\llama\Downloads\archive (8)"
archivos = [f for f in os.listdir(base_path) if f.endswith('.csv')]

if not archivos:
    print("No se encontró el archivo CSV en la carpeta.")
else:
    ruta_completa = os.path.join(base_path, archivos[0])
    print(f" Cargando: {ruta_completa}")

    # 3. EXTRACCIÓN
    df_raw = spark.read.csv(ruta_completa, header=True, inferSchema=True)

    # 4. TRANSFORMACIÓN (Limpieza del error de CAST)
    # Buscamos cualquier dígito (\d) en la columna 'Rating' y lo volvemos Entero
    df_limpio = df_raw.withColumn("Rating_Num", regexp_extract(col("Rating"), r"(\d)", 1).cast("int"))

    # 5. CREACIÓN DE LA TABLA DE HECHOS (Punto 5)
    # Filtramos nulos para evitar que filas malformadas rompan las consultas
    fact_amazon = df_limpio.select(
        col("Reviewer Name").alias("Usuario"),
        col("Country").alias("Pais"),
        col("Rating_Num").alias("Rating"),
        col("Review Date").alias("Fecha")
    ).filter(col("Rating").isNotNull())

    # Registrar vista temporal para SQL
    fact_amazon.createOrReplaceTempView("hechos_amazon")
    print("🚀 ETL Completado con éxito.")
    fact_amazon.show(5)

 Cargando: C:\Users\llama\Downloads\archive (8)\Amazon_Reviews.csv
🚀 ETL Completado con éxito.
+----------------+----+------+--------------------+
|         Usuario|Pais|Rating|               Fecha|
+----------------+----+------+--------------------+
|      Eugene ath|  US|     1|2024-09-16T13:44:...|
|Daniel ohalloran|  GB|     1|2024-09-16T18:26:...|
|        p fisher|  GB|     1|2024-09-16T21:47:...|
|       Greg Dunn|  AU|     1|2024-09-17T07:15:...|
|   Sheila Hannah|  GB|     1|2024-09-16T18:37:...|
+----------------+----+------+--------------------+
only showing top 5 rows

In [5]:
import os
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, regexp_extract, trim

# 1. Iniciar sesión
spark = SparkSession.builder.appName("Amazon_Final_Correction").getOrCreate()

# 2. Ruta
base_path = r"C:\Users\llama\Downloads\archive (8)"
archivo = os.path.join(base_path, "Amazon_Reviews.csv")

# 3. Leer CSV
df_raw = spark.read.csv(archivo, header=True, inferSchema=True)

# 4. Limpiar nombres de columnas (quitar espacios invisibles)
for col_name in df_raw.columns:
    df_raw = df_raw.withColumnRenamed(col_name, col_name.strip())

# 5. TRANSFORMACIÓN SEGURA (Uso de expr y try_cast)
# Primero extraemos el número, y si no puede convertirlo, devuelve NULL en vez de error
df_limpio = df_raw.withColumn("Rating_Num", 
    col("Rating").cast("string") # Aseguramos que sea string para regex
)
df_limpio = df_limpio.withColumn("Rating_Num", 
    regexp_extract(col("Rating_Num"), r"(\d)", 1)
)

# ESTA ES LA LÍNEA CLAVE: Usamos 'expr' para usar try_cast de SQL
from pyspark.sql.functions import expr
df_limpio = df_limpio.withColumn("Rating_Num", expr("try_cast(Rating_Num as int)"))

# 6. CREACIÓN DE TABLA DE HECHOS (Filtramos los que quedaron como NULL)
fact_amazon = df_limpio.select(
    col("Reviewer Name").alias("Usuario"),
    col("Country").alias("Pais"),
    col("Rating_Num").alias("Rating"),
    col("Review Date").alias("Fecha")
).filter(col("Rating").isNotNull()) 

# 7. REGISTRO Y CONSULTAS
fact_amazon.createOrReplaceTempView("hechos_final")

try:
    total = fact_amazon.count()
    print(f"--- REVISIÓN DE DATOS ---")
    print(f"Total de registros válidos cargados: {total}")
    fact_amazon.show(5)

    if total > 0:
        print("\n--- RESULTADO DE LAS CONSULTAS ---")
        # Consulta 1: Promedio
        spark.sql("SELECT 'Promedio Global' as Metrica, ROUND(AVG(Rating), 2) as Valor FROM hechos_final").show()
        # Consulta 2: Países
        spark.sql("SELECT Pais, COUNT(*) as Total FROM hechos_final GROUP BY Pais ORDER BY Total DESC LIMIT 5").show()
        # Consulta 3: Estrellas
        spark.sql("SELECT Rating, COUNT(*) as Cantidad FROM hechos_final GROUP BY Rating ORDER BY Rating DESC").show()
except Exception as e:
    print(f"Algo salió mal: {e}")

--- REVISIÓN DE DATOS ---
Total de registros válidos cargados: 21062
+----------------+----+------+--------------------+
|         Usuario|Pais|Rating|               Fecha|
+----------------+----+------+--------------------+
|      Eugene ath|  US|     1|2024-09-16T13:44:...|
|Daniel ohalloran|  GB|     1|2024-09-16T18:26:...|
|        p fisher|  GB|     1|2024-09-16T21:47:...|
|       Greg Dunn|  AU|     1|2024-09-17T07:15:...|
|   Sheila Hannah|  GB|     1|2024-09-16T18:37:...|
+----------------+----+------+--------------------+
only showing top 5 rows

--- RESULTADO DE LAS CONSULTAS ---
+---------------+-----+
|        Metrica|Valor|
+---------------+-----+
|Promedio Global| 2.19|
+---------------+-----+

+----+-----+
|Pais|Total|
+----+-----+
|  US| 9286|
|  GB| 7294|
|  CA|  708|
|  IN|  629|
|  IE|  242|
+----+-----+

+------+--------+
|Rating|Cantidad|
+------+--------+
|     5|    4528|
|     4|    1292|
|     3|     885|
|     2|    1228|
|     1|   13127|
|     0|       2|
+------+--------+

In [35]:
from IPython.display import display, HTML

conclusiones_finales_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">7. Conclusiones</h2>
    
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #27ae60;">
            <h3 style="margin-top: 0; color: #27ae60;">🛠️ Eficiencia Técnica</h3>
            <p>
                El uso de <b>Apache Spark</b> fue determinante para el éxito del proyecto. La capacidad de limpiar datos malformados (Ratings en texto) de manera distribuida permitió procesar miles de registros en segundos, algo que herramientas tradicionales no habrían logrado sin errores de memoria.
            </p>
        </div>

        <div style="flex: 1; background-color: #f4f4f4; padding: 20px; border-radius: 10px; border-left: 5px solid #e74c3c;">
            <h3 style="margin-top: 0; color: #e74c3c;">🎯 Valor de los Datos</h3>
            <p>
                La transición de un archivo CSV plano a un <b>Modelo Multidimensional (Estrella)</b> no solo organizó la información, sino que habilitó la generación de KPIs reales de satisfacción por país, permitiendo una toma de decisiones basada en datos limpios y estructurados.
            </p>
        </div>
    </div>
</div>
"""
display(HTML(conclusiones_finales_html))

In [28]:
referencias_finales_html = """
<div style="font-family: Arial, sans-serif; padding: 20px; line-height: 1.6;">
    <h2 style="color: #232f3e; border-bottom: 2px solid #ff9900; padding-bottom: 5px;">8. Referencias</h2>
    
    <div style="background-color: #f4f4f4; padding: 25px; border-radius: 10px; border-left: 5px solid #34495e;">
        <ul style="color: #333; list-style-type: disc; padding-left: 20px; font-size: 1.05em;">
            <li style="margin-bottom: 10px;">
                <b>Apache Spark Foundation (2026).</b> <i>PySpark Documentation: Spark SQL, Built-in Functions and DataFrames.</i> Recuperado de spark.apache.org
            </li>
            <li style="margin-bottom: 10px;">
                <b>Kaggle Dataset.</b> <i>Amazon Product Reviews: Customer Feedback and Global Ratings.</i> Recuperado de kaggle.com
            </li>
            <li style="margin-bottom: 10px;">
                <b>Kimball, Ralph.</b> <i>The Data Warehouse Toolkit: The Definitive Guide to Dimensional Modeling.</i> Wiley.
            </li>
            <li style="margin-bottom: 10px;">
                <b>Karau, H., & Warren, R. (2024).</b> <i>High Performance Spark: Best Practices for Scaling and Optimizing PySpark.</i> O'Reilly Media.
            </li>
        </ul>
    </div>
</div>
"""
display(HTML(referencias_finales_html))